#!/usr/bin/python3

import datetime
import os

print("Content-Type: text/html")
print()
print("<!DOCTYPE html>")
print("<html>")
print("<head><title>Current Time</title></head>")
print("<body>")
print("<h1>Current Server Time</h1>")
print(f"<p>The current time is: {datetime.datetime.now()}</p>")
print("<p>This page was generated by a Python CGI script.</p>")
print("<a href='/'>← Back to Home</a>")
print("</body>")
print("</html>")
